{{- if .Values.route.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "evefrontier.fullname" . }}-route
  labels:
    {{- include "evefrontier.route.labels" . | nindent 4 }}
spec:
  type: {{ .Values.route.service.type }}
  ports:
    - port: {{ .Values.route.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "evefrontier.route.selectorLabels" . | nindent 4 }}
{{- end }}
