{{- if .Values.scoutRange.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "evefrontier.fullname" . }}-scout-range
  labels:
    {{- include "evefrontier.scoutRange.labels" . | nindent 4 }}
spec:
  type: {{ .Values.scoutRange.service.type }}
  ports:
    - port: {{ .Values.scoutRange.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "evefrontier.scoutRange.selectorLabels" . | nindent 4 }}
{{- end }}
